project:
  type: website

execute: 
  freeze: auto

website:
  title: "Youfeng Zhou"
  twitter-card: true
  open-graph: true
  favicon: images/favicon.ico
  navbar:
    background: primary
    search: true
    left:
      - text: About
        file: about.qmd  
      - text: Projects
        file: projects/index.qmd
      - text: Posts
        file: posts/index.qmd
      - text: TILs
        file: tils/index.qmd
    right:
      - icon: github
        href: https://github.com/youfenglab
      - icon: twitter
        href: https://twitter.com/Joe_zhou14   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    